"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_GESTURE_THRESHOLDS = exports.DEFAULT_ANIMATION_DURATION = exports.BOTTOM_SHEET_HANDLE_WIDTH = exports.BOTTOM_SHEET_HANDLE_TOTAL_HEIGHT = exports.BOTTOM_SHEET_HANDLE_MARGIN_VERTICAL = exports.BOTTOM_SHEET_HANDLE_HEIGHT = exports.ANDROID_HEIGHT_OFFSET = void 0;
const DEFAULT_GESTURE_THRESHOLDS = exports.DEFAULT_GESTURE_THRESHOLDS = {
  closeVelocity: 500,
  closeFromTopVelocity: 2200,
  snapUpVelocity: -800,
  snapDownVelocity: 120,
  velocityProjectionFactor: 0.2,
  topSnapCloseRatio: 0.96,
  lowerSnapCloseRatio: 0.5
};
const DEFAULT_ANIMATION_DURATION = exports.DEFAULT_ANIMATION_DURATION = 250;
const BOTTOM_SHEET_HANDLE_HEIGHT = exports.BOTTOM_SHEET_HANDLE_HEIGHT = 4;
const BOTTOM_SHEET_HANDLE_WIDTH = exports.BOTTOM_SHEET_HANDLE_WIDTH = 32;
const BOTTOM_SHEET_HANDLE_MARGIN_VERTICAL = exports.BOTTOM_SHEET_HANDLE_MARGIN_VERTICAL = 8;
const BOTTOM_SHEET_HANDLE_TOTAL_HEIGHT = exports.BOTTOM_SHEET_HANDLE_TOTAL_HEIGHT = BOTTOM_SHEET_HANDLE_HEIGHT + BOTTOM_SHEET_HANDLE_MARGIN_VERTICAL * 2;
const ANDROID_HEIGHT_OFFSET = exports.ANDROID_HEIGHT_OFFSET = 16;
//# sourceMappingURL=defaults.js.map